### ISSUE TITLE
Classroom TODO

### ISSUE THREAD

**Issue by zmwebdev** [zmwebdev/python#10]
Renfe:
- [ ] Put functions into a file and then import

Python IDE:
- [ ] IDLE: clear screen
- [ ] IDLE: add workspace path
